### PR TITLE
As a concerned user, I want to know how and when I can get tested, so…

### PR DESCRIPTION
**Pull request by oianmol**
As a concerned user, I want to know how and when I can get tested, so that I can confirm whether or not I have COVID-19.

Added link https://www.cdc.gov/coronavirus/2019-ncov/symptoms-testing/testing.html

### CODE REVIEW

**Comment by SamIAmHarris** [comment]
On Android I am seeing the bottom dialog not fully expanded when going to home screen first time.
Screen Shot 2020-03-24 at 11 53 52 AM

**Comment by oianmol** [comment]
@SamIAmHarris I see, we may have to add a work around or use a modal bottom sheet instead for the content. what do you say ?

**Comment by Anmol92verma** [comment]
@SamIAmHarris  I have fixed it, and moved the view as a bottom sheet of the scaffold

**Comment by Anmol92verma** [comment]
Screenshot_20200324-225037

**Pull request merged**
